eureka:
  instance:
   # prefer-ip-address: true
    preferIpAddress: true
    #added hostname
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      #defaultZone: http://localhost:8761/eureka
      
okta:
  oauth2:
    issuer: https://dev-07651813.okta.com/oauth2/default
    audience: api://default
spring:
  zipkin:
    #baseUrl: http://zipkin-svc:9411
    baseUrl: http://localhost:9411
    #baseUrl: http://zipkin-svc:9411
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer   
